package br.com.claro.files;

public class ColunasJson {

	
	public static final String [] EVENTOS_DE_MENSAGENS_01 = {
			"items.eventType",
			"items.user",
			"items.time",
			"items.chat.chatId",
			"items.chat.helpdeskName",
			"items.chat.startedTime",
			"items.chat.startedBy",
			"items.chat.type",
			"items.chat.expireTime",
			"items.message.messageId",
			"items.message.sequenceNumber",
			"items.message.text",
			"items.message.attachment.attachmentId",
			"items.message.attachment.type",
			"items.message.attachment.latitude",
			"items.message.attachment.longitude",
			"items.message.attachment.filename",
			"items.message.attachment.downloadUrl",
			"items.message.attachment.activityId",
			"items.message.attachment.resourceInternalId",
			"items.message.attachment.resourceId",
			"items.message.attachment.date",
			"items.message.attachment.desc",
			"items.message.attachment.inventoryType",
			"items.message.attachment.inventoryId",
			"items.message.attachment.status",
			"items.message.attachment.quantity",
			"items.message.transaction.transactionId",
			"items.message.transaction.author",
			"items.message.transaction.startTime",
			"items.message.transaction.timeoutTime",
			"items.message.transaction.lastUpdatedBy",
			"items.message.transaction.operationStatus",
			"items.message.transaction.toAddress",
			"items.message.transaction.status",
			"items.participants.0.name",
			"items.participants.0.login",
			"items.participants.0.invitedBy",
			"items.participants.0.invitedTime",
			"items.participants.1.name",
			"items.participants.1.login",
			"items.participants.1.invitedBy",
			"items.participants.1.invitedTime",
			"items.participants.2.name",
			"items.participants.2.login",
			"items.participants.2.invitedBy",
			"items.participants.2.invitedTime",
			"items.participants.3.name",
			"items.participants.3.login",
			"items.participants.3.invitedBy",
			"items.participants.3.invitedTime",
			"items.participants.4.name",
			"items.participants.4.login",
			"items.participants.4.invitedBy",
			"items.participants.4.invitedTime",
			"items.participants.5.name",
			"items.participants.5.login",
			"items.participants.5.invitedBy",
			"items.participants.5.invitedTime",
			};
	
	public static final String [] EVENTOS_DE_MENSAGENS_03 = {
			"items.eventType",
			"items.user",
			"items.time",
			"items.statusChanges.login",
			"items.statusChanges.chatId",
			"items.statusChanges.messageId",
			"items.statusChanges.status",
			};
	
	
	public static final String []  RE_ROUTER = {

			"items.eventType",
			"items.time",
			"items.user",
			"items.activityDetails.activityId",
			"items.activityDetails.resourceId",
			"items.activityDetails.resourceInternalId",
			"items.activityDetails.date",
			"items.activityDetails.apptNumber",
			"items.activityDetails.customerNumber",
			"items.activityChanges.resourceInternalId",
			"items.activityChanges.positionInRoute",
			"items.activityChanges.resourceId",
			};
 	
	public static final String [] FORA_TOA_01= {
			"items.eventType",
			"items.time",
			"items.user",
			"items.applicationId",
			"items.activityDetails.activityId",
			"items.activityDetails.resourceId",
			"items.activityDetails.resourceInternalId",
			"items.activityDetails.date",
			"items.activityDetails.apptNumber",
			"items.activityDetails.customerNumber",
			"items.activityChanges.XA_TASK_ID_0",
			"items.activityChanges.XA_TASK_ID_1",
			"items.activityChanges.XA_TASK_ID_2",
			"items.activityChanges.XA_TASK_ID_3",
			"items.activityChanges.XA_TASK_ID_4",
			"items.activityChanges.XA_TASK_ID_5",
			"items.activityChanges.XA_TASK_ID_6",
			"items.activityChanges.XA_TASK_ID_7",
			"items.activityChanges.XA_TASK_ID_8",
			"items.activityChanges.XA_TASK_ID_9",
			"items.activityChanges.XA_CUSTOMER_CPF",
			"items.activityChanges.streetAddress",
			"items.activityChanges.workZone",
			"items.activityChanges.timeSlot",
			"items.activityChanges.activityType",
	};

public static final String [] FORA_TOA_02= {

		"items.eventType",
		"items.time",
		"items.user",
		"items.applicationId",
		"items.activityDetails.activityId",
		"items.activityDetails.resourceId",
		"items.activityDetails.resourceInternalId",
		"items.activityDetails.date",
		"items.activityDetails.apptNumber",
		"items.activityDetails.customerNumber",
		"items.activityChanges.XA_TASK_ID_0",
		"items.activityChanges.XA_TASK_ID_1",
		"items.activityChanges.XA_TASK_ID_2",
		"items.activityChanges.XA_TASK_ID_3",
		"items.activityChanges.XA_TASK_ID_4",
		"items.activityChanges.XA_TASK_ID_5",
		"items.activityChanges.XA_TASK_ID_6",
		"items.activityChanges.XA_TASK_ID_7",
		"items.activityChanges.XA_TASK_ID_8",
		"items.activityChanges.XA_TASK_ID_9",
		"items.activityChanges.XA_CUSTOMER_CPF",
		"items.activityChanges.streetAddress",
		"items.activityChanges.workZone",
		"items.activityChanges.timeSlot",
		"items.activityChanges.activityType",
};

}

